# Generated by Django 5.2 on 2025-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(default='-'),
        ),
    ]
