# Generated by Django 5.2 on 2025-04-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_restaurant_address_restaurant_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DurationField(default=0),
        ),
    ]
