# Generated by Django 5.2 on 2025-04-23 07:44

import datetime
from django.db import migrations, models
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_order_destination_order_status_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DurationField('time', models.DurationField(default=timedelta())),
        ),
    ]
