# Generated by Django 5.2 on 2025-04-23 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
