# Generated by Django 5.2 on 2025-05-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cooards',
            field=models.TextField(default='-'),
        ),
    ]
