# Generated by Django 5.2 on 2025-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_restaurant_cooards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cooards',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
