# Generated by Django 5.2 on 2025-05-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_restaurant_cooards_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='database.restaurant'),
        ),
    ]
