# Generated by Django 5.2 on 2025-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_restaurant_closing_time_restaurant_opening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
