# Generated by Django 5.2 on 2025-05-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_item_picture_alter_restaurant_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ImageField(blank=True, upload_to='VideoFrames/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RouteVideo', to='database.order')),
            ],
            options={
                'db_table': 'videoframe',
            },
        ),
    ]
