# Generated by Django 5.2 on 2025-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_videoframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='destination_lng',
            field=models.FloatField(null=True),
        ),
    ]
