# Generated by Django 5.2 on 2025-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_order_destination_lat_order_destination_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryp',
            name='Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
