# Generated by Django 5.2 on 2025-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_deliveryp_score_order_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='taken',
            field=models.DateTimeField(null=True),
        ),
    ]
