# Generated by Django 5.2 on 2025-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_order_review_order_completed_order_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Review',
            field=models.TextField(default='-'),
        ),
    ]
