# Generated by Django 5.2 on 2025-05-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_order_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryp',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
