# Generated by Django 5.2 on 2025-05-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_remove_deliveryp_miles_remove_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoframe',
            name='order',
        ),
        migrations.DeleteModel(
            name='FreqAddr',
        ),
        migrations.DeleteModel(
            name='VideoFrame',
        ),
    ]
