# Generated by Django 5.2 on 2025-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_remove_videoframe_order_delete_freqaddr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
